
NB! * There are a few scenarios in Java in which a finally block doesn't execute:
	> Application termination—The try or the catch block executes System.exit,
		which terminates the application
	> Fatal errors—A crash of the JVM or the OS

NB! * A try without resources must have either a catch or a finally. It may
have both as well.
Following constructs are valid:
	>  try{ } catch(Exception e){  }          	// no finally
	>  try{ } finally{  }          				// no catch
	>  try{ } catch(Exception e){  } finally{  }

NB! * In the case when both catch clause throws an exception and finally throws
another one, the Exception that is thrown in the last, is the Exception that is
thrown by the method to the caller. Meaning the FINALLY exception is ALWAYS the
thrown one.

NB! * You can have multiple catch blocks to catch different kinds of exceptions,
including exceptions that are subclasses of other exceptions. However, the catch
clause for more specific exceptions (i.e. a SubClassException) should come
before the catch clause for more general exceptions ( i.e. a
SuperClassException). Failure to do so results in a compiler error as the more
specific exception is unreachable.

* Watch out for code that returns a value from the catch block and modifies it
in the finally block. If a catch block returns a primitive data type, the
finally block can’t modify the value being returned by it. If a catch block
returns an object, the finally block can modify the value being returned by it.

NB! * Java doesn’t compile code if it contains unreachable statements.

* A try block may be followed by multiple catch blocks, and the catch blocks
may be followed by a single finally block.

* A try block may be followed by either a catch or a finally block or both. But
a finally block alone wouldn’t suffice if code in the try block throws a
checked exception. In this case, you need to catch the checked exception or
declare it to be thrown by your method. Otherwise your code won’t compile.

NB! * The try, catch, and finally blocks can’t exist independently.

NB! * The finally block can’t appear before a catch block.

NB! * A finally block always executes, regardless of whether the code throws
an exception.
